name: GitHub Metrics

on:
  schedule:
    - cron: "0 * * * *"  # har soatda bir marta
  workflow_dispatch:      # qo'lda ham ishga tushirish uchun

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: abudev0          # GitHub username'ing
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Tashkent

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
